#include "LexerTestSuite.h"

static LexerTester tester{Lexer{}};

// Positions (x/y) are intentionally not asserted by compareTokens, so expected
// tokens are built with dummy coordinates via this helper. Only token VALUES
// are compared. Error cases, by contrast, do assert row/column via GetError().
static Token T(TokenValue v) { return Token{ std::move(v), 0, 0 }; }

TEST_P(LexerTest, ExpressionTest) {
    tester.AssertTest(GetParam());
}

INSTANTIATE_TEST_SUITE_P (
    LexerTests,
    LexerTest,
    ::testing::Values(
        // ---- Numbers ----
        LexerTestCase{ "MultiDigitNumber", "42",
            std::vector<Token>{ T(NumericToken{42.0}) } },
        LexerTestCase{ "DecimalNumber", "3.14",
            std::vector<Token>{ T(NumericToken{3.14}) } },
        LexerTestCase{ "UnderscoreSeparatedNumber", "1_000",
            std::vector<Token>{ T(NumericToken{1000.0}) } },
        LexerTestCase{ "Zero", "0",
            std::vector<Token>{ T(NumericToken{0.0}) } },
        LexerTestCase{ "NumberThenKeyword", "5x",
            std::vector<Token>{ T(NumericToken{5.0}), T(KeywordToken{"x"}) } },

        // ---- Keywords / commands / paths ----
        LexerTestCase{ "SimpleKeyword", "echo",
            std::vector<Token>{ T(KeywordToken{"echo"}) } },
        LexerTestCase{ "KeywordWithDigits", "abc123",
            std::vector<Token>{ T(KeywordToken{"abc123"}) } },
        LexerTestCase{ "RelativePath", "./script",
            std::vector<Token>{ T(KeywordToken{"./script"}) } },
        LexerTestCase{ "HomePath", "~/file",
            std::vector<Token>{ T(KeywordToken{"~/file"}) } },
        LexerTestCase{ "DashFlag", "-l",
            std::vector<Token>{ T(KeywordToken{"-l"}) } },
        LexerTestCase{ "HyphenatedWord", "a-b",
            std::vector<Token>{ T(KeywordToken{"a-b"}) } },

        // ---- Variables ($) ----
        LexerTestCase{ "SimpleVariable", "$x",
            std::vector<Token>{ T(VariableToken{"x"}) } },
        LexerTestCase{ "UppercaseVariable", "$HOME",
            std::vector<Token>{ T(VariableToken{"HOME"}) } },
        LexerTestCase{ "UnderscoreVariable", "$my_var",
            std::vector<Token>{ T(VariableToken{"my_var"}) } },

        // ---- Functions (@) ----
        LexerTestCase{ "SimpleFunction", "@foo",
            std::vector<Token>{ T(FuncToken{"foo"}) } },

        // ---- Strings ----
        LexerTestCase{ "SimpleString", "\"hello\"",
            std::vector<Token>{ T(StringToken{"hello"}) } },
        LexerTestCase{ "EmptyString", "\"\"",
            std::vector<Token>{ T(StringToken{""}) } },
        LexerTestCase{ "StringWithSpaces", "\"hello world\"",
            std::vector<Token>{ T(StringToken{"hello world"}) } },
        LexerTestCase{ "StringOfDigits", "\"123\"",
            std::vector<Token>{ T(StringToken{"123"}) } },
        LexerTestCase{ "StringEscapedQuote", "\"a\\\"b\"",
            std::vector<Token>{ T(StringToken{"a\"b"}) } },

        // ---- Parentheses / brackets / braces ----
        LexerTestCase{ "FuncParens", "()",
            std::vector<Token>{ T(ParenthesesToken{Parentheses::FuncOpen}),
                                T(ParenthesesToken{Parentheses::FuncClose}) } },
        LexerTestCase{ "MiscBrackets", "[]",
            std::vector<Token>{ T(MiscParenthesesToken{MiscParentheses::BodyOpen}),
                                T(MiscParenthesesToken{MiscParentheses::BodyClose}) } },
        LexerTestCase{ "FuncBraces", "{}",
            std::vector<Token>{ T(FuncParenthesesToken{FuncParentheses::BodyOpen}),
                                T(FuncParenthesesToken{FuncParentheses::BodyClose}) } },
        LexerTestCase{ "NestedParens", "([{}])",
            std::vector<Token>{ T(ParenthesesToken{Parentheses::FuncOpen}),
                                T(MiscParenthesesToken{MiscParentheses::BodyOpen}),
                                T(FuncParenthesesToken{FuncParentheses::BodyOpen}),
                                T(FuncParenthesesToken{FuncParentheses::BodyClose}),
                                T(MiscParenthesesToken{MiscParentheses::BodyClose}),
                                T(ParenthesesToken{Parentheses::FuncClose}) } },

        // ---- Algebraic operators ----
        LexerTestCase{ "OperatorAdd", "+",
            std::vector<Token>{ T(AlgebraicOperatorToken{AlgebraicOperator::Add}) } },
        LexerTestCase{ "OperatorMul", "*",
            std::vector<Token>{ T(AlgebraicOperatorToken{AlgebraicOperator::Mul}) } },
        LexerTestCase{ "OperatorMod", "%",
            std::vector<Token>{ T(AlgebraicOperatorToken{AlgebraicOperator::Mod}) } },
        LexerTestCase{ "OperatorPow", "^",
            std::vector<Token>{ T(AlgebraicOperatorToken{AlgebraicOperator::Pow}) } },
        LexerTestCase{ "Subtraction", "5-3",
            std::vector<Token>{ T(NumericToken{5.0}),
                                T(AlgebraicOperatorToken{AlgebraicOperator::Sub}),
                                T(NumericToken{3.0}) } },
        LexerTestCase{ "LeadingMinusIsSub", "-5",
            std::vector<Token>{ T(AlgebraicOperatorToken{AlgebraicOperator::Sub}),
                                T(NumericToken{5.0}) } },
        LexerTestCase{ "SpacedSubtractionOfWords", "a - b",
            std::vector<Token>{ T(KeywordToken{"a"}),
                                T(AlgebraicOperatorToken{AlgebraicOperator::Sub}),
                                T(KeywordToken{"b"}) } },
        LexerTestCase{ "ArithmeticChain", "1+2*3",
            std::vector<Token>{ T(NumericToken{1.0}),
                                T(AlgebraicOperatorToken{AlgebraicOperator::Add}),
                                T(NumericToken{2.0}),
                                T(AlgebraicOperatorToken{AlgebraicOperator::Mul}),
                                T(NumericToken{3.0}) } },

        // ---- Logical operators ----
        LexerTestCase{ "LogicalAnd", "&&",
            std::vector<Token>{ T(LogicalOperatorToken{LogicalOperator::And}) } },
        LexerTestCase{ "LogicalOr", "||",
            std::vector<Token>{ T(LogicalOperatorToken{LogicalOperator::Or}) } },
        LexerTestCase{ "LogicalEquals", "==",
            std::vector<Token>{ T(LogicalOperatorToken{LogicalOperator::Equals}) } },
        LexerTestCase{ "LogicalNotEquals", "!=",
            std::vector<Token>{ T(LogicalOperatorToken{LogicalOperator::NotEquals}) } },
        LexerTestCase{ "LogicalNot", "!",
            std::vector<Token>{ T(LogicalOperatorToken{LogicalOperator::Not}) } },
        LexerTestCase{ "LogicalLesser", "<",
            std::vector<Token>{ T(LogicalOperatorToken{LogicalOperator::Lesser}) } },
        LexerTestCase{ "LogicalGreater", ">",
            std::vector<Token>{ T(LogicalOperatorToken{LogicalOperator::Greater}) } },
        LexerTestCase{ "LogicalLesserEquals", "<=",
            std::vector<Token>{ T(LogicalOperatorToken{LogicalOperator::LesserEquals}) } },
        LexerTestCase{ "LogicalGreaterEquals", ">=",
            std::vector<Token>{ T(LogicalOperatorToken{LogicalOperator::GreaterEquals}) } },
        LexerTestCase{ "Comparison", "1==2",
            std::vector<Token>{ T(NumericToken{1.0}),
                                T(LogicalOperatorToken{LogicalOperator::Equals}),
                                T(NumericToken{2.0}) } },

        // ---- Redirect signs ----
        LexerTestCase{ "RedirectRight", "->",
            std::vector<Token>{ T(SignToken{Sign::RedirectRight}) } },
        LexerTestCase{ "RedirectLeft", "<-",
            std::vector<Token>{ T(SignToken{Sign::RedirectLeft}) } },

        // ---- Newlines / statement separators ----
        LexerTestCase{ "Semicolon", ";",
            std::vector<Token>{ T(NewlineToken{}) } },
        LexerTestCase{ "Newline", "\n",
            std::vector<Token>{ T(NewlineToken{}) } },
        LexerTestCase{ "MultipleStatements", "a;b",
            std::vector<Token>{ T(KeywordToken{"a"}),
                                T(NewlineToken{}),
                                T(KeywordToken{"b"}) } },

        // ---- Comments / whitespace / empties ----
        LexerTestCase{ "CommentIsIgnored", "echo hi # a comment",
            std::vector<Token>{ T(KeywordToken{"echo"}), T(KeywordToken{"hi"}) } },
        LexerTestCase{ "EmptyInput", "",
            std::vector<Token>{} },
        LexerTestCase{ "WhitespaceOnly", "   \t ",
            std::vector<Token>{} },

        // ---- Realistic combinations ----
        LexerTestCase{ "CommandWithString", "echo \"hello world\"",
            std::vector<Token>{ T(KeywordToken{"echo"}), T(StringToken{"hello world"}) } },
        LexerTestCase{ "FunctionCall", "@func(1)",
            std::vector<Token>{ T(FuncToken{"func"}),
                                T(ParenthesesToken{Parentheses::FuncOpen}),
                                T(NumericToken{1.0}),
                                T(ParenthesesToken{Parentheses::FuncClose}) } },
        LexerTestCase{ "VariableInExpression", "$x + 5",
            std::vector<Token>{ T(VariableToken{"x"}),
                                T(AlgebraicOperatorToken{AlgebraicOperator::Add}),
                                T(NumericToken{5.0}) } },

        // ---- Complex / realistic multi-token cases ----
        LexerTestCase{ "AppendRedirectToFile", "cat log.txt >> all.log",
            std::vector<Token>{ T(KeywordToken{"cat"}), T(KeywordToken{"log.txt"}),
                                T(SignToken{Sign::AppendRight}), T(KeywordToken{"all.log"}) } },
        LexerTestCase{ "RedirectRightToFile", "echo hi -> out.txt",
            std::vector<Token>{ T(KeywordToken{"echo"}), T(KeywordToken{"hi"}),
                                T(SignToken{Sign::RedirectRight}), T(KeywordToken{"out.txt"}) } },
        LexerTestCase{ "ReadRedirect", "wc <- input.txt",
            std::vector<Token>{ T(KeywordToken{"wc"}), T(SignToken{Sign::RedirectLeft}),
                                T(KeywordToken{"input.txt"}) } },
        LexerTestCase{ "ChainedRedirects", "sort <- in.txt >> out.txt",
            std::vector<Token>{ T(KeywordToken{"sort"}), T(SignToken{Sign::RedirectLeft}),
                                T(KeywordToken{"in.txt"}), T(SignToken{Sign::AppendRight}),
                                T(KeywordToken{"out.txt"}) } },
        LexerTestCase{ "LogicalConjunctionOfCommands", "test -f file && echo exists",
            std::vector<Token>{ T(KeywordToken{"test"}), T(KeywordToken{"-f"}),
                                T(KeywordToken{"file"}), T(LogicalOperatorToken{LogicalOperator::And}),
                                T(KeywordToken{"echo"}), T(KeywordToken{"exists"}) } },
        LexerTestCase{ "ConditionalAndOrChain", "$x == 5 && echo yes || echo no",
            std::vector<Token>{ T(VariableToken{"x"}), T(LogicalOperatorToken{LogicalOperator::Equals}),
                                T(NumericToken{5.0}), T(LogicalOperatorToken{LogicalOperator::And}),
                                T(KeywordToken{"echo"}), T(KeywordToken{"yes"}),
                                T(LogicalOperatorToken{LogicalOperator::Or}),
                                T(KeywordToken{"echo"}), T(KeywordToken{"no"}) } },
        LexerTestCase{ "NestedFunctionCalls", "@outer(@inner(5))",
            std::vector<Token>{ T(FuncToken{"outer"}), T(ParenthesesToken{Parentheses::FuncOpen}),
                                T(FuncToken{"inner"}), T(ParenthesesToken{Parentheses::FuncOpen}),
                                T(NumericToken{5.0}), T(ParenthesesToken{Parentheses::FuncClose}),
                                T(ParenthesesToken{Parentheses::FuncClose}) } },
        LexerTestCase{ "ArithmeticWithParensAndVariable", "(1 + 2) * $x",
            std::vector<Token>{ T(ParenthesesToken{Parentheses::FuncOpen}), T(NumericToken{1.0}),
                                T(AlgebraicOperatorToken{AlgebraicOperator::Add}), T(NumericToken{2.0}),
                                T(ParenthesesToken{Parentheses::FuncClose}),
                                T(AlgebraicOperatorToken{AlgebraicOperator::Mul}), T(VariableToken{"x"}) } },
        LexerTestCase{ "DivisionWithVariable", "$total / 2",
            std::vector<Token>{ T(VariableToken{"total"}),
                                T(AlgebraicOperatorToken{AlgebraicOperator::Div}), T(NumericToken{2.0}) } },
        LexerTestCase{ "ConditionalBlockBody", "if ($x > 0) { echo pos }",
            std::vector<Token>{ T(KeywordToken{"if"}), T(ParenthesesToken{Parentheses::FuncOpen}),
                                T(VariableToken{"x"}), T(LogicalOperatorToken{LogicalOperator::Greater}),
                                T(NumericToken{0.0}), T(ParenthesesToken{Parentheses::FuncClose}),
                                T(FuncParenthesesToken{FuncParentheses::BodyOpen}),
                                T(KeywordToken{"echo"}), T(KeywordToken{"pos"}),
                                T(FuncParenthesesToken{FuncParentheses::BodyClose}) } },
        LexerTestCase{ "NestedEscapedQuotesInString", "echo \"He said \\\"hi\\\"\"",
            std::vector<Token>{ T(KeywordToken{"echo"}), T(StringToken{"He said \"hi\""}) } },
        LexerTestCase{ "MixedArithmeticExpression", "$a * ($b + 1) - 5 / $c",
            std::vector<Token>{ T(VariableToken{"a"}), T(AlgebraicOperatorToken{AlgebraicOperator::Mul}),
                                T(ParenthesesToken{Parentheses::FuncOpen}), T(VariableToken{"b"}),
                                T(AlgebraicOperatorToken{AlgebraicOperator::Add}), T(NumericToken{1.0}),
                                T(ParenthesesToken{Parentheses::FuncClose}),
                                T(AlgebraicOperatorToken{AlgebraicOperator::Sub}), T(NumericToken{5.0}),
                                T(AlgebraicOperatorToken{AlgebraicOperator::Div}), T(VariableToken{"c"}) } },
        LexerTestCase{ "MultiLineScript", "echo start\n@process($data)\necho done",
            std::vector<Token>{ T(KeywordToken{"echo"}), T(KeywordToken{"start"}), T(NewlineToken{}),
                                T(FuncToken{"process"}), T(ParenthesesToken{Parentheses::FuncOpen}),
                                T(VariableToken{"data"}), T(ParenthesesToken{Parentheses::FuncClose}),
                                T(NewlineToken{}), T(KeywordToken{"echo"}), T(KeywordToken{"done"}) } },
        LexerTestCase{ "PipelineReadAndAppendWithLogical", "grep foo <- data.txt && echo found >> log.txt",
            std::vector<Token>{ T(KeywordToken{"grep"}), T(KeywordToken{"foo"}),
                                T(SignToken{Sign::RedirectLeft}), T(KeywordToken{"data.txt"}),
                                T(LogicalOperatorToken{LogicalOperator::And}), T(KeywordToken{"echo"}),
                                T(KeywordToken{"found"}), T(SignToken{Sign::AppendRight}),
                                T(KeywordToken{"log.txt"}) } },

        // ---- For loops ----
        LexerTestCase{ "ForLoopHeader", "for($i <- 0; $i < 50; $i <- $i+1) { cp test }",
            std::vector<Token>{ T(KeywordToken{"for"}), T(ParenthesesToken{Parentheses::FuncOpen}),
                                T(VariableToken{"i"}), T(SignToken{Sign::RedirectLeft}), T(NumericToken{0.0}),
                                T(NewlineToken{}),
                                T(VariableToken{"i"}), T(LogicalOperatorToken{LogicalOperator::Lesser}),
                                T(NumericToken{50.0}), T(NewlineToken{}),
                                T(VariableToken{"i"}), T(SignToken{Sign::RedirectLeft}),
                                T(VariableToken{"i"}), T(AlgebraicOperatorToken{AlgebraicOperator::Add}),
                                T(NumericToken{1.0}), T(ParenthesesToken{Parentheses::FuncClose}),
                                T(FuncParenthesesToken{FuncParentheses::BodyOpen}),
                                T(KeywordToken{"cp"}), T(KeywordToken{"test"}),
                                T(FuncParenthesesToken{FuncParentheses::BodyClose}) } },
        LexerTestCase{ "ForRedirectVsComparison", "$i <- 0; $i < 50",
            std::vector<Token>{ T(VariableToken{"i"}), T(SignToken{Sign::RedirectLeft}), T(NumericToken{0.0}),
                                T(NewlineToken{}),
                                T(VariableToken{"i"}), T(LogicalOperatorToken{LogicalOperator::Lesser}),
                                T(NumericToken{50.0}) } },
        LexerTestCase{ "ForLoopTightSpacing", "for($i<-0;$i<3;$i<-$i+1){cp x}",
            std::vector<Token>{ T(KeywordToken{"for"}), T(ParenthesesToken{Parentheses::FuncOpen}),
                                T(VariableToken{"i"}), T(SignToken{Sign::RedirectLeft}), T(NumericToken{0.0}),
                                T(NewlineToken{}),
                                T(VariableToken{"i"}), T(LogicalOperatorToken{LogicalOperator::Lesser}),
                                T(NumericToken{3.0}), T(NewlineToken{}),
                                T(VariableToken{"i"}), T(SignToken{Sign::RedirectLeft}),
                                T(VariableToken{"i"}), T(AlgebraicOperatorToken{AlgebraicOperator::Add}),
                                T(NumericToken{1.0}), T(ParenthesesToken{Parentheses::FuncClose}),
                                T(FuncParenthesesToken{FuncParentheses::BodyOpen}),
                                T(KeywordToken{"cp"}), T(KeywordToken{"x"}),
                                T(FuncParenthesesToken{FuncParentheses::BodyClose}) } },
        LexerTestCase{ "ForLoopGreaterEqualsCondition", "for($n <- 10; $n >= 0; $n <- $n-1) { cp $n }",
            std::vector<Token>{ T(KeywordToken{"for"}), T(ParenthesesToken{Parentheses::FuncOpen}),
                                T(VariableToken{"n"}), T(SignToken{Sign::RedirectLeft}), T(NumericToken{10.0}),
                                T(NewlineToken{}),
                                T(VariableToken{"n"}), T(LogicalOperatorToken{LogicalOperator::GreaterEquals}),
                                T(NumericToken{0.0}), T(NewlineToken{}),
                                T(VariableToken{"n"}), T(SignToken{Sign::RedirectLeft}),
                                T(VariableToken{"n"}), T(AlgebraicOperatorToken{AlgebraicOperator::Sub}),
                                T(NumericToken{1.0}), T(ParenthesesToken{Parentheses::FuncClose}),
                                T(FuncParenthesesToken{FuncParentheses::BodyOpen}),
                                T(KeywordToken{"cp"}), T(VariableToken{"n"}),
                                T(FuncParenthesesToken{FuncParentheses::BodyClose}) } },

        // ---- Errors (these DO assert row/column) ----
        LexerTestCase{ "ErrIncompleteString", "\"abc",
            LexerError{ "Incomplete string: abc", 1, 1 } },
        LexerTestCase{ "ErrIncompleteNumber", "3.",
            LexerError{ "Incomplete number: 3..", 1, 1 } },
        LexerTestCase{ "ErrDoubleVariableSign", "$$",
            LexerError{ "Variable identifier found in variable mode", 2, 1 } },
        LexerTestCase{ "ErrDoubleFunctionSign", "@@",
            LexerError{ "Function identifier found in function mode", 2, 1 } },
        LexerTestCase{ "ErrUnknownCharQuestion", "?",
            LexerError{ "Unknown character encountered: ?", 1, 1 } },
        LexerTestCase{ "ErrUnknownCharColon", ":",
            LexerError{ "Unknown character encountered: :", 1, 1 } }
    ),
    [](const testing::TestParamInfo<LexerTest::ParamType>& param) {
        return std::get<0>(param.param);
    }
);
